version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-venta
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: venta_maquinaria_db
      MYSQL_USER: venta
      MYSQL_PASSWORD: venta123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: app-venta-maquinaria
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/venta_maquinaria_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: venta
      SPRING_DATASOURCE_PASSWORD: venta123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-venta
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

volumes:
  db_data:
  sonar_data:
  sonar_extensions:
  sonar_logs: