version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-venta
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: venta_maquinaria_db
      MYSQL_USER: venta
      MYSQL_PASSWORD: venta123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
